### ISSUE TITLE
Try using php linter

### ISSUE THREAD

**Issue by s1mark** [jnsngy/ByteMe#325]
```yaml
- name: PHP Syntax Checker (Lint)
  uses: StephaneBour/actions-php-lint@8.2
  with:
    dir: './src'
```

**Comment by s1mark** [comment]
```yaml
name: 'php linter'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'lint'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      uses: StephaneBour/actions-php-lint@8.2
      with:
        dir: './src'
```
